language: python

matrix:
  include:
    - python: 3.7
    - python: 3.8
    - python: 3.9

dist: xenial

cache: false

before_install:
- npm install npm@latest -g
- sudo apt-get update
- sudo apt-get install pandoc
- pip install pypandoc

install:
  - pip install --upgrade pip
  - pip -V
  - pip install tox-travis

script:
  - make deps dev_deps install_project

before_deploy:
- pip install bump2version
- nvm install 12
- npm install @semantic-release/changelog
- npm install @semantic-release/exec
- npm install @semantic-release/git
- npm install @semantic-release/github


deploy:
- provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    python: '3.5'
    branch: master

- provider: pypi
  user: __token__
  password: $PYPI_TOKEN
  repository: https://upload.pypi.org/legacy
  skip_cleanup: true
  on:
    python: '3.6'
    tags: true
